export const CREATE_BOX_REQUEST = 'CREATE_BOX_REQUEST';
export const CREATE_BOX_SUCCESS = 'CREATE_BOX_SUCCESS';
export const CREATE_BOX_FAIL = 'CREATE_BOX_FAIL';

export const GET_BOX_REQUEST = 'GET_BOX_REQUEST';
export const GET_BOX_SUCCESS = 'GET_BOX_SUCCESS';
export const GET_BOX_FAIL = 'GET_BOX_FAIL';

export const DELETE_BOX_REQUEST = 'DELETE_BOX_REQUEST';
export const DELETE_BOX_SUCCESS = 'DELETE_BOX_SUCCESS';
export const DELETE_BOX_FAIL = ' DELETE_BOX_FAIL';

export const GET_DETAIL_BOX_REQUEST = 'GET_DETAIL_BOX_REQUEST';
export const GET_DETAIL_BOX_SUCCESS = 'GET_DETAIL_BOX_SUCCESS';
export const GET_DETAIL_BOX_FAIL = 'GET_DETAIL_BOX_FAIL';

export const UPDATE_BOX_REQUEST = 'UPDATE_BOX_REQUEST';
export const UPDATE_BOX_SUCCESS = 'UPDATE_BOX_SUCCESS';
export const UPDATE_BOX_FAIL = ' UPDATE_BOX_FAIL';

export const GET_BARCODE_SIZE_REQUEST = 'GET_BARCODE_SIZE_REQUEST';
export const GET_BARCODE_SIZE_SUCCESS = 'GET_BARCODE_SIZE_SUCCESS';
export const GET_BARCODE_SIZE_FAIL = 'GET_BARCODE_SIZE_FAIL';
