export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAIL = 'GET_ORDER_FAIL';

export const GET_PACKAGE_DIVIDE_REQUEST = 'GET_PACKAGE_DIVIDE_REQUEST';
export const GET_PACKAGE_DIVIDE_SUCCESS = 'GET_PACKAGE_DIVIDE_SUCCESS';
export const GET_PACKAGE_DIVIDE_FAIL = 'GET_PACKAGE_DIVIDE_FAIL';

export const CREATE_MANUAL_SHIP_REQUEST = 'CREATE_MANUAL_SHIP_REQUEST';
export const CREATE_MANUAL_SHIP_SUCCESS = 'CREATE_MANUAL_SHIP_SUCCESS';
export const CREATE_MANUAL_SHIP_FAIL = 'CREATE_MANUAL_SHIP_FAIL';

export const SET_ORDER_DETAIL = 'SET_ORDER_DETAIL';

export const CREATE_INVOICE_QUICK_BOOK_REQUEST = 'CREATE_INVOICE_QUICK_BOOK_REQUEST';
export const CREATE_INVOICE_QUICK_BOOK_SUCCESS = 'CREATE_INVOICE_QUICK_BOOK_SUCCESS';
export const CREATE_INVOICE_QUICK_BOOK_FAIL = ' CREATE_INVOICE_QUICK_BOOK_FAIL';

export const CREATE_INVOICE_REQUEST = 'CREATE_INVOICE_REQUEST';
export const CREATE_INVOICE_SUCCESS = 'CREATE_INVOICE_SUCCESS';
export const CREATE_INVOICE_FAIL = ' CREATE_INVOICE_FAIL';

export const CANCEL_ORDER_REQUEST = 'CANCEL_ORDER_REQUEST';
export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS';
export const CANCEL_ORDER_FAIL = ' CANCEL_ORDER_FAIL';

export const GET_COUNT_NEW_ORDER_REQUEST = 'GET_COUNT_NEW_ORDER_REQUEST';
export const GET_COUNT_NEW_ORDER_SUCCESS = 'GET_COUNT_NEW_ORDER_SUCCESS';
export const GET_COUNT_NEW_ORDER_FAIL = 'GET_COUNT_NEW_ORDER_FAIL';

export const GET_NEW_ORDER_REQUEST = 'GET_NEW_ORDER_REQUEST';
export const GET_NEW_ORDER_SUCCESS = 'GET_NEW_ORDER_SUCCESS';
export const GET_NEW_ORDER_FAIL = 'GET_NEW_ORDER_FAIL';

export const CREATE_ACKNOWLEDGE_REQUEST = 'CREATE_ACKNOWLEDGE_REQUEST';
export const CREATE_ACKNOWLEDGE_SUCCESS = 'CREATE_ACKNOWLEDGE_SUCCESS';
export const CREATE_ACKNOWLEDGE_FAIL = 'CREATE_ACKNOWLEDGE_FAIL';
