export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAIL = 'GET_ORDER_FAIL';

export const GET_PACKAGE_DIVIDE_REQUEST = 'GET_PACKAGE_DIVIDE_REQUEST';
export const GET_PACKAGE_DIVIDE_SUCCESS = 'GET_PACKAGE_DIVIDE_SUCCESS';
export const GET_PACKAGE_DIVIDE_FAIL = 'GET_PACKAGE_DIVIDE_FAIL';

export const CREATE_MANUAL_SHIP_REQUEST = 'CREATE_MANUAL_SHIP_REQUEST';
export const CREATE_MANUAL_SHIP_SUCCESS = 'CREATE_MANUAL_SHIP_SUCCESS';
export const CREATE_MANUAL_SHIP_FAIL = 'CREATE_MANUAL_SHIP_FAIL';

export const SET_ORDER_DETAIL = 'SET_ORDER_DETAIL';