export const CREATE_PACKAGE_RULE_REQUEST = 'CREATE_PACKAGE_RULE_REQUEST';
export const CREATE_PACKAGE_RULE_SUCCESS = 'CREATE_PACKAGE_RULE_SUCCESS';
export const CREATE_PACKAGE_RULE_FAIL = 'CREATE_PACKAGE_RULE_FAIL';
