export const CREATE_PACKAGE_RULE_REQUEST = 'CREATE_PACKAGE_RULE_REQUEST';
export const CREATE_PACKAGE_RULE_SUCCESS = 'CREATE_PACKAGE_RULE_SUCCESS';
export const CREATE_PACKAGE_RULE_FAIL = 'CREATE_PACKAGE_RULE_FAIL';

export const GET_PACKAGE_RULE_REQUEST = 'GET_PACKAGE_RULE_REQUEST';
export const GET_PACKAGE_RULE_SUCCESS = 'GET_PACKAGE_RULE_SUCCESS';
export const GET_PACKAGE_RULE_FAIL = 'GET_PACKAGE_RULE_FAIL';

export const DELETE_PACKAGE_RULE_REQUEST = 'DELETE_PACKAGE_RULE_REQUEST';
export const DELETE_PACKAGE_RULE_SUCCESS = 'DELETE_PACKAGE_RULE_SUCCESS';
export const DELETE_PACKAGE_RULE_FAIL = ' DELETE_PACKAGE_RULE_FAIL';

export const GET_DETAIL_PACKAGE_RULE_REQUEST = 'GET_DETAIL_PACKAGE_RULE_REQUEST';
export const GET_DETAIL_PACKAGE_RULE_SUCCESS = 'GET_DETAIL_PACKAGE_RULE_SUCCESS';
export const GET_DETAIL_PACKAGE_RULE_FAIL = 'GET_DETAIL_PACKAGE_RULE_FAIL';

export const UPDATE_PACKAGE_RULE_REQUEST = 'UPDATE_PACKAGE_RULE_REQUEST';
export const UPDATE_PACKAGE_RULE_SUCCESS = 'UPDATE_PACKAGE_RULE_SUCCESS';
export const UPDATE_PACKAGE_RULE_FAIL = ' UPDATE_PACKAGE_RULE_FAIL';
