export const CREATE_PACKAGE_RULE_REQUEST = 'CREATE_PACKAGE_RULE_REQUEST';
export const CREATE_PACKAGE_RULE_SUCCESS = 'CREATE_PACKAGE_RULE_SUCCESS';
export const CREATE_PACKAGE_RULE_FAIL = 'CREATE_PACKAGE_RULE_FAIL';

export const GET_PACKAGE_RULE_REQUEST = 'GET_PACKAGE_RULE_REQUEST';
export const GET_PACKAGE_RULE_SUCCESS = 'GET_PACKAGE_RULE_SUCCESS';
export const GET_PACKAGE_RULE_FAIL = 'GET_PACKAGE_RULE_FAIL';

export const DELETE_PACKAGE_RULE_REQUEST = 'DELETE_PACKAGE_RULE_REQUEST';
export const DELETE_PACKAGE_RULE_SUCCESS = 'DELETE_PACKAGE_RULE_SUCCESS';
export const DELETE_PACKAGE_RULE_FAIL = ' DELETE_PACKAGE_RULE_FAIL';
