export const CREATE_SFTP_REQUEST = 'CREATE_SFTP_REQUEST';
export const CREATE_SFTP_SUCCESS = 'CREATE_SFTP_SUCCESS';
export const CREATE_SFTP_FAIL = 'CREATE_SFTP_FAIL';

export const GET_SFTP_REQUEST = 'GET_SFTP_REQUEST';
export const GET_SFTP_SUCCESS = 'GET_SFTP_SUCCESS';
export const GET_SFTP_FAIL = 'GET_SFTP_FAIL';

export const GET_SFTP_DETAIL_REQUEST = 'GET_SFTP_DETAIL_REQUEST';
export const GET_SFTP_DETAIL_SUCCESS = 'GET_SFTP_DETAIL_SUCCESS';
export const GET_SFTP_DETAIL_FAIL = 'GET_SFTP_DETAIL_FAIL';

export const UPDATE_SFTP_REQUEST = 'UPDATE_SFTP_REQUEST';
export const UPDATE_SFTP_SUCCESS = 'UPDATE_SFTP_SUCCESS';
export const UPDATE_SFTP_FAIL = 'UPDATE_SFTP_FAIL';

export const DELETE_SFTP_REQUEST = 'DELETE_SFTP_REQUEST';
export const DELETE_SFTP_SUCCESS = 'DELETE_SFTP_SUCCESS';
export const DELETE_SFTP_FAIL = ' DELETE_SFTP_FAIL';

export const GET_RETAILER_REQUEST = 'GET_RETAILER_REQUEST';
export const GET_RETAILER_SUCCESS = 'GET_RETAILER_SUCCESS';
export const GET_RETAILER_FAIL = 'GET_RETAILER_FAIL';

export const DOWNLOAD_ORDER_REQUEST = 'DOWNLOAD_ORDER_REQUEST';
export const DOWNLOAD_ORDER_SUCCESS = 'DOWNLOAD_ORDER_SUCCESS';
export const DOWNLOAD_ORDER_FAIL = 'DOWNLOAD_ORDER_FAIL';
