export const CREATE_GS1_REQUEST = 'CREATE_GS1_REQUEST';
export const CREATE_GS1_SUCCESS = 'CREATE_GS1_SUCCESS';
export const CREATE_GS1_FAIL = 'CREATE_GS1_FAIL';

export const GET_GS1_REQUEST = 'GET_GS1_REQUEST';
export const GET_GS1_SUCCESS = 'GET_GS1_SUCCESS';
export const GET_GS1_FAIL = 'GET_GS1_FAIL';

export const DELETE_GS1_REQUEST = 'DELETE_GS1_REQUEST';
export const DELETE_GS1_SUCCESS = 'DELETE_GS1_SUCCESS';
export const DELETE_GS1_FAIL = ' DELETE_GS1_FAIL';

export const GET_DETAIL_GS1_REQUEST = 'GET_DETAIL_GS1_REQUEST';
export const GET_DETAIL_GS1_SUCCESS = 'GET_DETAIL_GS1_SUCCESS';
export const GET_DETAIL_GS1_FAIL = 'GET_DETAIL_GS1_FAIL';

export const UPDATE_GS1_REQUEST = 'UPDATE_GS1_REQUEST';
export const UPDATE_GS1_SUCCESS = 'UPDATE_GS1_SUCCESS';
export const UPDATE_GS1_FAIL = ' UPDATE_GS1_FAIL';
