export const LAYOUTS = {
  GRID: 'grid',
  LIST: 'list'
};

export const DataCountryRegion = [
  'AF',
  'AX',
  'AL',
  'DZ',
  'AS',
  'AD',
  'AO',
  'AI',
  'AQ',
  'AG',
  'AR',
  'AM',
  'AW',
  'AU',
  'AT',
  'AZ',
  'BS',
  'BH',
  'BD',
  'BB',
  'BY',
  'BE',
  'BZ',
  'BJ',
  'BM',
  'BT',
  'BO',
  'BA',
  'BW',
  'BV',
  'BR',
  'IO',
  'BN',
  'BG',
  'BF',
  'BI',
  'KH',
  'CM',
  'CA',
  'CV',
  'KY',
  'CF',
  'TD',
  'CL',
  'CN',
  'CX',
  'CC',
  'CO',
  'KM',
  'CG',
  'CD',
  'CK',
  'CR',
  'CI',
  'HR',
  'CU',
  'CY',
  'CZ',
  'DK',
  'DJ',
  'DM',
  'DO',
  'EC',
  'EG',
  'SV',
  'GQ',
  'ER',
  'EE',
  'ET',
  'FK',
  'FO',
  'FJ',
  'FI',
  'FR',
  'GF',
  'PF',
  'TF',
  'GA',
  'GM',
  'GE',
  'DE',
  'GH',
  'GI',
  'GR',
  'GL',
  'GD',
  'GP',
  'GU',
  'GT',
  'GG',
  'GN',
  'GW',
  'GY',
  'HT',
  'HM',
  'VA',
  'HN',
  'HK',
  'HU',
  'IS',
  'IN',
  'ID',
  'IR',
  'IQ',
  'IE',
  'IM',
  'IL',
  'IT',
  'JM',
  'JP',
  'JE',
  'JO',
  'KZ',
  'KE',
  'KI',
  'KP',
  'KR',
  'KW',
  'KG',
  'LA',
  'LV',
  'LB',
  'LS',
  'LR',
  'LY',
  'LI',
  'LT',
  'LU',
  'MO',
  'MK',
  'MG',
  'MW',
  'MY',
  'MV',
  'ML',
  'MT',
  'MH',
  'MQ',
  'MR',
  'MU',
  'YT',
  'MX',
  'FM',
  'MD',
  'MC',
  'MN',
  'MS',
  'MA',
  'MZ',
  'MM',
  'NA',
  'NR',
  'NP',
  'NL',
  'AN',
  'NC',
  'NZ',
  'NI',
  'NE',
  'NG',
  'NU',
  'NF',
  'MP',
  'NO',
  'OM',
  'PK',
  'PW',
  'PS',
  'PA',
  'PG',
  'PY',
  'PE',
  'PH',
  'PN',
  'PL',
  'PT',
  'PR',
  'QA',
  'RE',
  'RO',
  'RU',
  'RW',
  'SH',
  'KN',
  'LC',
  'PM',
  'VC',
  'WS',
  'SM',
  'ST',
  'SA',
  'SN',
  'CS',
  'SC',
  'SL',
  'SG',
  'SK',
  'SI',
  'SB',
  'SO',
  'ZA',
  'GS',
  'ES',
  'LK',
  'SD',
  'SR',
  'SJ',
  'SZ',
  'SE',
  'CH',
  'SY',
  'TW',
  'TJ',
  'TZ',
  'TH',
  'TL',
  'TG',
  'TK',
  'TO',
  'TT',
  'TN',
  'TR',
  'TM',
  'TC',
  'TV',
  'UG',
  'UA',
  'AE',
  'GB',
  'US',
  'UM',
  'UY',
  'UZ',
  'VU',
  'VE',
  'VN',
  'VG',
  'VI',
  'WF',
  'EH',
  'YE',
  'ZM',
  'ZW'
];

export function base64ToImage(base64String: string) {
  const img = `data:image/png;base64,${base64String}`;
  return img;
}

export const minDate = () => {
  const today = new Date().toISOString().split('T')[0];
  return today;
};

export const phoneRegExp =
  /^((\\+[1-9]{1,4}[ \\-]*)|(\\([0-9]{2,3}\\)[ \\-]*)|([0-9]{2,4})[ \\-]*)*?[0-9]{3,4}?[ \\-]*[0-9]{3,4}?$/;

export const optionsPerPage = [
  {
    label: 5,
    value: 5
  },
  {
    label: 10,
    value: 10
  },
  {
    label: 25,
    value: 25
  },
  {
    label: 50,
    value: 50
  },
  {
    label: 100,
    value: 100
  },
  {
    label: 'All',
    value: -1
  }
];

export function resetOrientation(
  srcBase64: string,
  srcOrientation: any,
  callback: (data: any) => void
) {
  var img = new Image();

  img.onload = function () {
    var width = img.width,
      height = img.height,
      canvas = document.createElement('canvas'),
      ctx = canvas.getContext('2d');

    if (4 < srcOrientation && srcOrientation < 9) {
      canvas.width = height;
      canvas.height = width;
    } else {
      canvas.width = width;
      canvas.height = height;
    }

    switch (srcOrientation) {
      case 2:
        ctx?.transform(-1, 0, 0, 1, width, 0);
        break;
      case 3:
        ctx?.transform(-1, 0, 0, -1, width, height);
        break;
      case 4:
        ctx?.transform(1, 0, 0, -1, 0, height);
        break;
      case 5:
        ctx?.transform(0, 1, 1, 0, 0, 0);
        break;
      case 6:
        ctx?.transform(0, 1, -1, 0, height, 0);
        break;
      case 7:
        ctx?.transform(0, -1, -1, 0, height, width);
        break;
      case 8:
        ctx?.transform(0, -1, 1, 0, 0, width);
        break;
      default:
        break;
    }

    ctx?.drawImage(img, 0, 0);
    callback(canvas.toDataURL());
  };

  img.src = srcBase64;
}

export const headerProductAliasCSV = [
  { label: 'SKU Alias', key: 'sku' },
  { label: 'Product', key: 'product' },
  { label: 'Package Quantity', key: 'sku_quantity' },
  { label: 'Merchant SKU', key: 'merchant_sku' },
  { label: 'Vendor SKU', key: 'vendor_sku' },
  { label: 'Retailer', key: 'retailer' },
  { label: 'Merchant ID', key: 'merchant_id' },
  { label: 'UPC', key: 'upc' },
  { label: 'Retailer Warehouse', key: 'retailer_warehouse' },
  { label: 'QTY On Hand', key: 'qty_on_hand' },
  { label: 'Next Available QTY', key: 'next_available_qty' },
  { label: 'Next Available Date', key: 'next_available_date' }
];

export const keyBodyUploadFile = [
  { label: 'SKU Alias', key: 'sku' },
  { label: 'Product', key: 'product_sku' },
  { label: 'Package Quantity', key: 'sku_quantity' },
  { label: 'Merchant SKU', key: 'merchant_sku' },
  { label: 'Vendor SKU', key: 'vendor_sku' },
  { label: 'Retailer', key: 'retailer_name' },
  { label: 'Merchant ID', key: 'retailer_merchant_id' },
  { label: 'UPC', key: 'upc' },
  { label: 'Retailer Warehouse', key: 'warehouse_name' },
  { label: 'QTY On Hand', key: 'qty_on_hand' },
  { label: 'Next Available QTY', key: 'next_available_qty' },
  { label: 'Next Available Date', key: 'next_available_day' }
];

export const DATA_REFERENCE = [
  {
    value: 'customer_reference',
    label: 'Customer reference'
  },
  {
    value: 'po_number',
    label: 'PO number'
  },
  {
    value: 'invoice_number',
    label: 'Invoice number'
  },
  {
    value: 'department_number',
    label: 'Department number'
  }
];

export const ReferenceNameRegex = /{{.*?}}/g;

export const errorServiceShipping = 'The value within {{}} is invalid, please double-check';

export const ORDER_STATUS = {
  Opened: 'Opened',
  Acknowledged: 'Acknowledged',
  Shipped: 'Shipped',
  'Shipment Confirmed': 'Shipment Confirmed',
  Invoiced: 'Invoiced',
  'Invoice Confirmed': 'Invoice Confirmed',
  Cancelled: 'Cancelled',
  'Bypassed Acknowledge': 'Bypassed Acknowledge',
  Backorder: 'Backorder',
  'Partly Shipped': 'Partly Shipped',
  'Partly Shipped Confirmed': 'Partly Shipped Confirmed',
  Returned: 'Returned'
};

export const MERCHANDISE_CODE = {
  D2S: 'D2S',
  X2S: 'X2S',
  D2C: 'D2C'
};

export const URL_SANDBOX = 'https://app.sandbox.qbo.intuit.com';

export const LOWES = 'lowes';
export const CREATED = 'created';
export const SUBMITTED = 'submitted';
export const VOIDED = 'voided';

export const SHIP_METHOD = [
  { value: 'ALKM_G2', label: 'A & M Transport Inc - Basic Service' },
  { value: 'PYLR', label: 'A. Duie Pyle Inc.' },
  { value: 'AACT', label: 'AAA Cooper Transportation' },
  { value: 'ABFS_G2', label: 'ABF - Basic Service' },
  { value: 'AUEP', label: 'Accurate Transportation Inc' },
  { value: 'ADAN', label: 'Adams & Sons Transportation' },
  { value: 'ADTS_G2', label: 'Advantage Transportaion (Dart Advantage) - Basic Service' },
  { value: 'AGHC', label: 'AGH Truck Lines Inc' },
  { value: 'AITW', label: 'AIT Worldwide Logistics' },
  { value: 'ANSH', label: 'Alliance Shippers Inc.' },
  { value: 'AMZK', label: 'Amazon Freight Intermodal' },
  { value: 'AFXN', label: 'Amazon Logistics Inc.' },
  { value: 'ACRL', label: 'American Central Transport Inc.' },
  { value: 'AOIE', label: 'American National Logistics' },
  { value: 'AMFK_CG', label: 'Amil Freight Inc - Ground' },
  { value: 'ATLY', label: 'Anderson Transportation And Logistics LLC' },
  { value: 'ARVY', label: 'Arrive Logistics' },
  { value: 'ATUR', label: 'Artur Express' },
  { value: 'ASLM', label: 'Ascend Llc' },
  { value: 'ASAF', label: 'Associated Air Freight' },
  { value: 'AVRT_G2', label: 'Averitt Express - Basic Service' },
  { value: 'ADSJ', label: 'Averitt Truckload' },
  { value: 'BHDR', label: 'Backhaul Direct' },
  { value: 'BTTE', label: 'Barnes Transportation Services Inc.' },
  { value: 'BNUN', label: 'Barr-Nunn Transportation LLC' },
  { value: 'BAYJ', label: 'Bay And Bay Transportation Services' },
  { value: 'BNYE', label: 'Benkait Logistics LLC' },
  { value: 'BSCG', label: 'Best Cartage Inc' },
  { value: 'BWLT_CG', label: 'Best Way Logistics Inc - Ground' },
  { value: 'BGXP', label: 'Big G Express Inc.' },
  { value: 'BGLF', label: 'Blue Grace Logistics' },
  { value: 'BDLC', label: 'Bluegrass Dedicated LLC' },
  { value: 'BORN', label: 'Bohren Logistics Inc' },
  { value: 'BOMN', label: 'Bowman, D M Inc' },
  { value: 'BRXS', label: "Braun's Express (service level unspecified)" },
  { value: 'BWNM', label: 'Brown Transportation Systems LLC' },
  { value: 'RBTW', label: 'C.H. Robinson Worldwide Inc.' },
  { value: 'AZFJ_G2', label: 'C1 Freight - Basic Service' },
  { value: 'CG_CG', label: 'Canada Post - Regular Parcel' },
  { value: 'CVLJ', label: 'Caravan Logistics' },
  { value: 'CCNI_CG', label: 'Cardinal Logistics Management Corporation - Ground' },
  { value: 'CGOR', label: 'Cargo Transporters Inc' },
  { value: 'CENF', label: 'Central Freight Lines' },
  { value: 'CETR', label: 'Central Transport Inc.' },
  { value: 'CEVA_G2', label: 'CEVA Logistics - Basic Service' },
  { value: 'CEVA_CG', label: 'CEVA Logistics - Ground' },
  { value: 'CGFR', label: 'Challenger Freight Systems, Inc.' },
  { value: 'CFAA', label: 'Cheema Freightliners LLC' },
  { value: 'CHNS', label: 'Christenson Transportation' },
  { value: 'CCLI_CG', label: 'Commercial Carpet Logistics - Ground' },
  { value: 'CNWY', label: 'Con-Way Freight' },
  { value: 'CVYI', label: 'Convoy Inc' },
  { value: 'CRPE', label: 'Corporate Traffic' },
  { value: 'MPZM', label: 'Costlow Enterprises LLC' },
  { value: 'CWAW', label: 'Cowan Systems Brokerage' },
  { value: 'CXTQ', label: 'Cox Transfer Inc' },
  { value: 'CLLQ', label: 'Coyote Logistics Llc' },
  { value: 'CRCR', label: 'Crete Carrier Corporation' },
  { value: 'CRLC', label: 'Cest Logistics Inc' },
  { value: 'CGLY', label: 'Custom Global Logistics (service unspecified)' },
  { value: 'CTBV', label: 'Custom Transport, Inc.' },
  { value: 'DTNF', label: 'Davis Transfer' },
  { value: 'DAYR', label: 'Day &amp; Ross' },
  { value: 'DYLT', label: 'Daylight Transport' },
  { value: 'DAFG', label: 'Dayton Freight' },
  { value: 'DEDA', label: 'Dedicated Carriers' },
  { value: 'DCLH', label: 'Dedicated Logistics Services' },
  { value: 'DDDN_G2', label: 'Delta Distribution - Basic Service' },
  { value: 'DPHE', label: 'Dependable Highway Express' },
  { value: 'DGRD', label: 'Dieselgrid Llc' },
  { value: 'DMRG_G2', label: 'DM Transportation Management Services - Basic Service' },
  { value: 'DNFV', label: 'DMH Express LLC' },
  { value: 'DHRN', label: 'Dohrn Transfer Co.' },
  { value: 'DGLH', label: 'Dreaming Green Logistics Llc' },
  { value: 'DUPN', label: 'Dupre Logistics Llc' },
  { value: 'ETCA', label: 'E-Transport Carriers Inc' },
  { value: 'EANC_PM', label: 'Eastern Connection Ground' },
  { value: 'ECCK_CG', label: 'ECCO Transport Inc - Ground' },
  { value: 'ERGN', label: 'Emerge Transportation' },
  { value: 'EPSG_G2', label: 'Epes Logistics Services - Basic Service' },
  { value: 'EPES', label: 'Epes Transport System Inc.' },
  { value: 'ERDB', label: 'Erdner Brothers' },
  { value: 'EEIE', label: 'Erives Enterprises Inc.' },
  { value: 'ESNL', label: 'Estenson Logistics LLC' },
  { value: 'EXLA', label: 'Estes Express Lines' },
  { value: 'EFWW_G2', label: 'Estes Forwarding Worldwide - Basic Service' },
  { value: 'EPOT', label: 'Experior Transport' },
  { value: 'AYSD', label: 'Express Freight' },
  { value: 'EXXA', label: 'Exxact Express Inc' },
  { value: 'FX', label: 'FedEx (service level unspecified)' },
  { value: 'FX2D', label: 'FedEx 2Day' },
  { value: 'FEDX_3D', label: 'FedEx Express Saver' },
  { value: 'FEDF', label: 'FedEx Freight Economy' },
  { value: 'FEDP', label: 'FedEx Freight Priority' },
  { value: 'FEDX', label: 'FedEx Ground' },
  { value: 'FXSP', label: 'FedEx Ground Economy' },
  { value: 'FEDX_ET', label: 'FedEx Ground, Signature Required' },
  { value: 'FEDH', label: 'FedEx Home Delivery' },
  { value: 'FXND', label: 'FedEx Next Day (Standard)' },
  { value: 'FEDX_NM', label: 'FedEx Priority Overnight' },
  { value: 'FCTI', label: 'First Choice Transport, Inc' },
  { value: 'FCSW', label: 'First Class Carriers' },
  { value: 'FZMK', label: 'Fitzmark, Inc.' },
  { value: 'FLSJ', label: 'F L S Transportation Services' },
  { value: 'FWDN', label: 'Forward Air Inc.' },
  { value: 'FWRA_CG', label: 'Forward LTL - Ground' },
  { value: 'FCSY_DS', label: 'Frontline Freight - Threshold Service' },
  { value: 'FSBS', label: 'Full Sail Logistics LLC' },
  { value: 'FCLC', label: 'Fulmer, Carroll Logistics Corporation' },
  { value: 'GPTC', label: 'G &amp; P Trucking Company Inc' },
  { value: 'GPTD', label: 'G &amp; P Trucking Company Inc (Dedicated)' },
  { value: 'GPSF', label: 'G &amp; P Trucking Company Inc (Super Fleet Division)' },
  { value: 'GDAL', label: 'G&amp;D Integrated' },
  { value: 'GLQV', label: 'Giltner Logistics' },
  { value: 'AFNS', label: 'Global Tranz (AFN)' },
  { value: 'CEEG', label: 'Global Tranz (Circle 8)' },
  { value: 'GPAB', label: 'GP Transco' },
  { value: 'GLXS', label: 'Grane Logistics Express LLC' },
  { value: 'GLXS_CG', label: 'Grane Logistics Express LLC - Ground' },
  { value: 'HAEI', label: 'Heartland Express Services Inc' },
  { value: 'HRCF', label: 'Hercules Freight (service unspecified)' },
  { value: 'HMDT', label: 'Hmd Trucking' },
  { value: 'HNRF', label: 'HNRY Logistics Inc' },
  { value: 'HGTN_G2', label: 'Hogan Transports - Basic Service' },
  { value: 'HWDQ', label: 'Hollywood Delivery Service' },
  { value: 'HWCC', label: 'Howl Transportation LLC' },
  { value: 'HUBG', label: 'Hub Group (intermodal division)' },
  { value: 'HUBO', label: 'Hub Group Inc' },
  { value: 'ITNS', label: 'International Transportation Services Inc.' },
  { value: 'HJCS', label: 'JB Hunt - Dedicated Contract Services' },
  { value: 'HJBI', label: 'JB Hunt Intermodal' },
  { value: 'HJBM', label: 'JB Hunt Marketplace' },
  { value: 'HJBT', label: 'JB Hunt_1' },
  { value: 'JFRE', label: 'Jeep Freight' },
  { value: 'JFRE_CG', label: 'Jeep Freight - Ground' },
  { value: 'JTXC', label: 'Joe Tex Xpress LLC' },
  { value: 'JPLQ', label: 'JP Logistics Inc.' },
  { value: 'JPLQ_CG', label: 'JP Logistics Inc. - Ground' },
  { value: 'KNIG', label: 'Knight Transportation Inc' },
  { value: 'LDAL', label: 'Land Sea Air' },
  { value: 'LTAO', label: 'Landair Transport Inc' },
  { value: 'LRGR', label: 'Landstar Ranger Inc' },
  { value: 'BOUF', label: 'Le Bouf Transport LLC' },
  { value: 'LEZP', label: 'Legacy Trucking 33 LLC' },
  { value: 'MHUW', label: 'MAD Hauling LLC' },
  { value: 'MOLP', label: 'Madison Logistics' },
  { value: 'MGXB', label: 'Magellan Transport Logistics' },
  { value: 'MFRC_G2', label: 'Mainfreight - Basic Service' },
  { value: 'MWLK', label: 'Meadow Lark Agency Inc' },
  { value: 'MSLV', label: 'Mesilla Valley Transportation' },
  { value: 'MWDP_G2', label: 'Metropolitan Warehouse & Delivery - Basic Service' },
  { value: 'MLXP', label: 'Milan Express Co.' },
  { value: 'MTNF', label: 'Millis Transfer' },
  { value: 'MJBF_G2', label: 'MJB Freight Systems - Basic Service' },
  { value: 'MHKC', label: 'Mohawk Carpet Transportation of GA LLC' },
  { value: 'MRQW', label: 'Moran Logistics' },
  { value: 'MEPC', label: 'Moret Enterprise Llc' },
  { value: 'MHLC', label: 'Motion Holdings LLC' },
  { value: 'MTVL_G2', label: 'Mountain Valley Express - Basic Service' },
  { value: 'MKXG', label: 'Mx Solutions' },
  { value: 'NMTF', label: 'N & M Transfer' },
  { value: 'NAVE', label: 'Navajo Express, Inc.' },
  { value: 'NIND_G2', label: 'Need It Now Delivers - Basic Service' },
  { value: 'NIND_R1', label: 'Need It Now Delivers - Room Choice' },
  { value: 'NIND_DS', label: 'Need It Now Delivers - Threshold Service' },
  { value: 'NPME', label: 'New Penn Motor Express' },
  { value: 'NWIQ_CG', label: 'New Wave International Cargo Inc - Ground' },
  { value: 'NWPI_G2', label: 'NewAge - Basic Service' },
  { value: 'NFIL', label: 'Nfi Interactive Logistics Llc' },
  { value: 'NFIA', label: 'NFI Interactive Logistics' },
  { value: 'NAFT_G2', label: 'NFI Transportation - Basic Service' },
  { value: 'NDLV', label: 'NonstopDelivery' },
  { value: 'NDLV_09', label: 'NonstopDelivery - Room Choice, Install' },
  { value: 'NDLV_DS', label: 'NonstopDelivery - Threshold Service' },
  { value: 'NRMA', label: 'Normandin Transit Inc' },
  { value: 'NUSH', label: 'Nussbaum Transportation Services Inc' },
  { value: 'OAKH', label: 'Oak Harbor Freight Lines, Inc.' },
  { value: 'OHTP', label: 'Ohio Transport' },
  { value: 'ODFL', label: 'Old Dominion' },
  { value: 'OTHR', label: 'Other' },
  { value: 'OWEL', label: 'Outwest Express LLC' },
  { value: 'OZRK', label: 'Ozark Motor Lines Inc.' },
  { value: 'PAMT_G2', label: 'P A M Transport Inc - Basic Service' },
  { value: 'PGLI_G2', label: 'Pacer Transportation Solutions - Basic Service' },
  { value: 'PASC', label: 'Paschall Truck Lines' },
  { value: 'PAAF', label: 'Pilot Freight Services' },
  { value: 'PITD', label: 'PITT Ohio' },
  { value: 'PWEQ', label: 'Power Express Inc.' },
  { value: 'PTAG', label: 'Premier Transportation' },
  { value: 'PDCM', label: 'Product Distribution Company' },
  { value: 'PTGO', label: 'PTG Logistics LLC' },
  { value: 'QPMT', label: 'Quantum Premium Transport (J B Hunt Intermodal)' },
  { value: 'RNLO', label: 'R & L Carriers' },
  { value: 'RGLN_G2', label: 'Radiant Global Logistics - Basic Service' },
  { value: 'RCSC', label: 'RCS Logistics Inc' },
  { value: 'RETR', label: 'Re Transportation' },
  { value: 'RCXB', label: 'Red Classic Transit LLC' },
  { value: 'RDRV', label: 'Reed Transport Services Inc.' },
  { value: 'RDRV_CG', label: 'Reed Transport Services Inc. - Ground' },
  { value: 'RISF', label: 'RIST Transport' },
  { value: 'RDFS', label: 'Roadrunner Transportation' },
  { value: 'BNRP_G2', label: 'Robert Bearden Inc. - Basic Service' },
  { value: 'BNRP_CG', label: 'Robert Bearden Inc. - Ground' },
  { value: 'ROEV', label: 'Roehl Transport, Inc.' },
  { value: 'RYXV', label: 'Roadone Intermodalogistics' },
  { value: 'RLUM', label: 'Rts Holdings Inc' },
  { value: 'RILK', label: 'Ryder dedicated' },
  { value: 'RYDD', label: 'Ryder Integrated Logistics Inc.' },
  { value: 'SAIA', label: 'Saia Motor Freight' },
  { value: 'SBFH', label: 'Sbf Transportation Llc' },
  { value: 'SLCY', label: 'Schneider National Carriers Inc' },
  { value: 'SCDS', label: 'Schneider National Carriers Inc-Optimodal' },
  { value: 'SCNN', label: 'Schneider National Carriers Inc.' },
  { value: 'SNCK', label: 'Schneider National Carriers Inc. (Truck/Rail)' },
  { value: 'SCNN_G2', label: 'Schneider National Carriers Inc. - Basic Service' },
  { value: 'SJRG', label: 'Schugel J and R Trucking Inc' },
  { value: 'SDLC', label: 'SDLC Transport Inc' },
  { value: 'SEKW_G2', label: 'Seko - Basic Service' },
  { value: 'SEKW_09', label: 'Seko - Room Choice, Install' },
  { value: 'SEKW_DS', label: 'Seko - Threshold Service' },
  { value: 'SGDB_CG', label: 'Shotgun Distribution - Ground' },
  { value: 'SMTA', label: 'Smith Transport Inc' },
  { value: 'SEFL', label: 'Southeastern Freight Lines' },
  { value: 'SMTL', label: 'Southwestern Motor Transport' },
  { value: 'STDF', label: 'Standard Forwarding LLC' },
  { value: 'SMMT', label: 'Summit Trucking LLC' },
  { value: 'SUTO', label: 'Sun Transportation Systems' },
  { value: 'SUON_G2', label: 'Sutton Transport - Basic Service' },
  { value: 'SWFT', label: 'Swift Transport (service unspecified)' },
  { value: 'TDUM', label: 'TDS Unlimited' },
  { value: 'TTMS', label: 'Total Transportation of Mississippi' },
  { value: 'TQYL', label: 'TQL Total Quality Logistics' },
  { value: 'TRBR_CG', label: 'Trailer Bridge Inc - Ground' },
  { value: 'TLNI_CG', label: 'Trans Lines Inc - Ground' },
  { value: 'TAMI', label: 'TransAm Trucking' },
  { value: 'UFLB', label: 'Uber Freight' },
  { value: 'UNSW', label: 'Unis Llc' },
  { value: 'UNSP', label: 'Unspecified' },
  { value: 'UPSN', label: 'UPS (service level unspecified)' },
  { value: 'UB', label: 'UPS 2nd Day Air' },
  { value: 'UPSN_3D', label: 'UPS 3 Day Select' },
  { value: 'UPGS', label: 'UPS Freight (service level unspecified)' },
  { value: 'UG', label: 'UPS Ground' },
  { value: 'UX', label: 'UPS Ground, Signature Required' },
  { value: 'UPSN_FC', label: 'UPS Mail Innovations - Standard' },
  { value: 'UR', label: 'UPS Next Day Air' },
  { value: 'UPSN_PM', label: 'UPS Next Day Air Saver' },
  { value: 'UPSN_ST', label: 'UPS SurePost 1 lb or greater' },
  { value: 'USXI', label: 'US Xpress' },
  { value: 'USIT', label: 'USA Truck Inc' },
  { value: 'USIL_CG', label: 'USA Truck Inc - Ground' },
  { value: 'HMES', label: 'USF Holland' },
  { value: 'RETL', label: 'USF Reddaway' },
  { value: 'USPS', label: 'USPS (service level unspecified)' },
  { value: 'QM', label: 'USPS Express Mail' },
  { value: 'US', label: 'USPS First Class Mail' },
  { value: 'USPS_BC', label: 'USPS Parcel Select - Non Presort' },
  { value: 'PM', label: 'USPS Priority Mail' },
  { value: 'VEXP', label: 'Venture Express Inc.' },
  { value: 'VSXP', label: 'Vision Express' },
  { value: 'VOUM', label: 'Volume Transportation Inc.' },
  { value: 'VOUM_CG', label: 'Volume Transportation Inc. - Ground' },
  { value: 'WARD', label: 'WARD Trucking' },
  { value: 'WATW_CG', label: 'Watsontown Trucking Company - Ground' },
  { value: 'WENP', label: 'Werner Enterprises Inc' },
  { value: 'WENP_CG', label: 'Werner Enterprises Inc - Ground' },
  { value: 'WMMI', label: 'Werner Multimodel' },
  { value: 'WESM', label: 'West Motor Freight Of Pa' },
  { value: 'WSGS', label: 'West Side Transport Inc' },
  { value: 'WSXF', label: 'Western Express (Flatbed Division)' },
  { value: 'WSXI', label: 'Western Express Inc' },
  { value: 'WSLD_G2', label: 'Westwood Shipping Lines - Basic Service' },
  { value: 'WEXF', label: 'Worldwide Express' },
  { value: 'XPOL', label: 'XPO Logistics LLC' },
  { value: 'XGSI_G2', label: 'Xpress Global Systems - Basic Service' },
  { value: 'XGSI_R1', label: 'Xpress Global Systems - Room Choice' },
  { value: 'XGSI_09', label: 'Xpress Global Systems - Room Choice, Install' },
  { value: 'XGSI_DS', label: 'Xpress Global Systems - Threshold Service' },
  { value: 'YFSY_G2', label: 'Yellow (YRC) - Basic Service' },
  { value: 'YRC', label: 'York Railway Company' },
  { value: 'RDWY_CG', label: 'YRC - Ground' },
  { value: 'ZMTL', label: 'Zimmerman Truck Lines, Inc.' }
];
