export const CREATE_BARCODE_SIZE_REQUEST = 'CREATE_BARCODE_SIZE_REQUEST';
export const CREATE_BARCODE_SIZE_SUCCESS = 'CREATE_BARCODE_SIZE_SUCCESS';
export const CREATE_BARCODE_SIZE_FAIL = 'CREATE_BARCODE_SIZE_FAIL';

export const GET_BARCODE_SIZE_REQUEST = 'GET_BARCODE_SIZE_REQUEST';
export const GET_BARCODE_SIZE_SUCCESS = 'GET_BARCODE_SIZE_SUCCESS';
export const GET_BARCODE_SIZE_FAIL = 'GET_BARCODE_SIZE_FAIL';

export const DELETE_BARCODE_SIZE_REQUEST = 'DELETE_BARCODE_SIZE_REQUEST';
export const DELETE_BARCODE_SIZE_SUCCESS = 'DELETE_BARCODE_SIZE_SUCCESS';
export const DELETE_BARCODE_SIZE_FAIL = ' DELETE_BARCODE_SIZE_FAIL';

export const GET_DETAIL_BARCODE_SIZE_REQUEST = 'GET_DETAIL_BARCODE_SIZE_REQUEST';
export const GET_DETAIL_BARCODE_SIZE_SUCCESS = 'GET_DETAIL_BARCODE_SIZE_SUCCESS';
export const GET_DETAIL_BARCODE_SIZE_FAIL = 'GET_DETAIL_BARCODE_SIZE_FAIL';

export const UPDATE_BARCODE_SIZE_REQUEST = 'UPDATE_BARCODE_SIZE_REQUEST';
export const UPDATE_BARCODE_SIZE_SUCCESS = 'UPDATE_BARCODE_SIZE_SUCCESS';
export const UPDATE_BARCODE_SIZE_FAIL = ' UPDATE_BARCODE_SIZE_FAIL';
