export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_FAIL = 'CREATE_PRODUCT_FAIL';

export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL';

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAIL = ' DELETE_PRODUCT_FAIL';

export const GET_PACKAGE_RULE_REQUEST = 'GET_PACKAGE_RULE_REQUEST';
export const GET_PACKAGE_RULE_SUCCESS = 'GET_PACKAGE_RULE_SUCCESS';
export const GET_PACKAGE_RULE_FAIL = ' GET_PACKAGE_RULE_FAIL';

export const GET_PRODUCT_DETAIL_REQUEST = 'GET_PRODUCT_DETAIL_REQUEST';
export const GET_PRODUCT_DETAIL_SUCCESS = 'GET_PRODUCT_DETAIL_SUCCESS';
export const GET_PRODUCT_DETAIL_FAIL = ' GET_PRODUCT_DETAIL_FAIL';

export const DELETE_BULK_PRODUCT_REQUEST = 'DELETE_BULK_PRODUCT_REQUEST';
export const DELETE_BULK_PRODUCT_SUCCESS = 'DELETE_BULK_PRODUCT_SUCCESS';
export const DELETE_BULK_PRODUCT_FAIL = ' DELETE_BULK_PRODUCT_FAIL';

export const CREATE_BULK_PRODUCT_REQUEST = 'CREATE_BULK_PRODUCT_REQUEST';
export const CREATE_BULK_PRODUCT_SUCCESS = 'CREATE_BULK_PRODUCT_SUCCESS';
export const CREATE_BULK_PRODUCT_FAIL = ' CREATE_BULK_PRODUCT_FAIL';

export const GET_RELOAD_QB_REQUEST = 'GET_RELOAD_QB_REQUEST';
export const GET_RELOAD_QB_SUCCESS = 'GET_RELOAD_QB_SUCCESS';
export const GET_RELOAD_QB_FAIL = ' GET_RELOAD_QB_FAIL';
