export const CREATE_PRODUCT_SERIES_REQUEST = 'CREATE_PRODUCT_SERIES_REQUEST';
export const CREATE_PRODUCT_SERIES_SUCCESS = 'CREATE_PRODUCT_SERIES_SUCCESS';
export const CREATE_PRODUCT_SERIES_FAIL = 'CREATE_PRODUCT_SERIES_FAIL';

export const GET_PRODUCT_SERIES_REQUEST = 'GET_PRODUCT_SERIES_REQUEST';
export const GET_PRODUCT_SERIES_SUCCESS = 'GET_PRODUCT_SERIES_SUCCESS';
export const GET_PRODUCT_SERIES_FAIL = 'GET_PRODUCT_SERIES_FAIL';

export const GET_PRODUCT_SERIES_DETAIL_REQUEST = 'GET_PRODUCT_SERIES_DETAIL_REQUEST';
export const GET_PRODUCT_SERIES_DETAIL_SUCCESS = 'GET_PRODUCT_SERIES_DETAIL_SUCCESS';
export const GET_PRODUCT_SERIES_DETAIL_FAIL = 'GET_PRODUCT_SERIES_DETAIL_FAIL';

export const UPDATE_PRODUCT_SERIES_REQUEST = 'UPDATE_PRODUCT_SERIES_REQUEST';
export const UPDATE_PRODUCT_SERIES_SUCCESS = 'UPDATE_PRODUCT_SERIES_SUCCESS';
export const UPDATE_PRODUCT_SERIES_FAIL = 'UPDATE_PRODUCT_SERIES_FAIL';

export const DELETE_PRODUCT_SERIES_REQUEST = 'DELETE_PRODUCT_SERIES_REQUEST';
export const DELETE_PRODUCT_SERIES_SUCCESS = 'DELETE_PRODUCT_SERIES_SUCCESS';
export const DELETE_PRODUCT_SERIES_FAIL = ' DELETE_PRODUCT_SERIES_FAIL';

export const DELETE_BULK_PRODUCT_SERIES_REQUEST = 'DELETE_BULK_PRODUCT_SERIES_REQUEST';
export const DELETE_BULK_PRODUCT_SERIES_SUCCESS = 'DELETE_BULK_PRODUCT_SERIES_SUCCESS';
export const DELETE_BULK_PRODUCT_SERIES_FAIL = ' DELETE_BULK_PRODUCT_SERIES_FAIL';

export const GET_RETAILER_REQUEST = 'GET_RETAILER_REQUEST';
export const GET_RETAILER_SUCCESS = 'GET_RETAILER_SUCCESS';
export const GET_RETAILER_FAIL = 'GET_RETAILER_FAIL';

export const CREATE_PRODUCT_WAREHOUSE_REQUEST = 'CREATE_PRODUCT_WAREHOUSE_REQUEST';
export const CREATE_PRODUCT_WAREHOUSE_SUCCESS = 'CREATE_PRODUCT_WAREHOUSE_SUCCESS';
export const CREATE_PRODUCT_WAREHOUSE_FAIL = 'CREATE_PRODUCT_WAREHOUSE_FAIL';

export const UPDATE_PRODUCT_STATIC_BULK_REQUEST = 'UPDATE_PRODUCT_STATIC_BULK_REQUEST';
export const UPDATE_PRODUCT_STATIC_BULK_SUCCESS = 'UPDATE_PRODUCT_STATIC_BULK_SUCCESS';
export const UPDATE_PRODUCT_STATIC_BULK_FAIL = 'UPDATE_PRODUCT_STATIC_BULK_FAIL';

export const UPDATE_LIVE_PRODUCT_SERIES_REQUEST = 'UPDATE_LIVE_PRODUCT_SERIES_REQUEST';
export const UPDATE_LIVE_PRODUCT_SERIES_SUCCESS = 'UPDATE_LIVE_PRODUCT_SERIES_SUCCESS';
export const UPDATE_LIVE_PRODUCT_SERIES_FAIL = 'UPDATE_LIVE_PRODUCT_SERIES_FAIL';
