export const CREATE_PRODUCT_ALIAS_REQUEST = 'CREATE_PRODUCT_ALIAS_REQUEST';
export const CREATE_PRODUCT_ALIAS_SUCCESS = 'CREATE_PRODUCT_ALIAS_SUCCESS';
export const CREATE_PRODUCT_ALIAS_FAIL = 'CREATE_PRODUCT_ALIAS_FAIL';

export const GET_PRODUCT_ALIAS_REQUEST = 'GET_PRODUCT_ALIAS_REQUEST';
export const GET_PRODUCT_ALIAS_SUCCESS = 'GET_PRODUCT_ALIAS_SUCCESS';
export const GET_PRODUCT_ALIAS_FAIL = 'GET_PRODUCT_ALIAS_FAIL';

export const GET_PRODUCT_ALIAS_DETAIL_REQUEST = 'GET_PRODUCT_ALIAS_DETAIL_REQUEST';
export const GET_PRODUCT_ALIAS_DETAIL_SUCCESS = 'GET_PRODUCT_ALIAS_DETAIL_SUCCESS';
export const GET_PRODUCT_ALIAS_DETAIL_FAIL = 'GET_PRODUCT_ALIAS_DETAIL_FAIL';

export const UPDATE_PRODUCT_ALIAS_REQUEST = 'UPDATE_PRODUCT_ALIAS_REQUEST';
export const UPDATE_PRODUCT_ALIAS_SUCCESS = 'UPDATE_PRODUCT_ALIAS_SUCCESS';
export const UPDATE_PRODUCT_ALIAS_FAIL = 'UPDATE_PRODUCT_ALIAS_FAIL';

export const DELETE_PRODUCT_ALIAS_REQUEST = 'DELETE_PRODUCT_ALIAS_REQUEST';
export const DELETE_PRODUCT_ALIAS_SUCCESS = 'DELETE_PRODUCT_ALIAS_SUCCESS';
export const DELETE_PRODUCT_ALIAS_FAIL = ' DELETE_PRODUCT_ALIAS_FAIL';

export const GET_RETAILER_REQUEST = 'GET_RETAILER_REQUEST';
export const GET_RETAILER_SUCCESS = 'GET_RETAILER_SUCCESS';
export const GET_RETAILER_FAIL = 'GET_RETAILER_FAIL';

export const CREATE_PRODUCT_WAREHOUSE_REQUEST = 'CREATE_PRODUCT_WAREHOUSE_REQUEST';
export const CREATE_PRODUCT_WAREHOUSE_SUCCESS = 'CREATE_PRODUCT_WAREHOUSE_SUCCESS';
export const CREATE_PRODUCT_WAREHOUSE_FAIL = 'CREATE_PRODUCT_WAREHOUSE_FAIL';

export const UPDATE_PRODUCT_STATIC_BULK_REQUEST = 'UPDATE_PRODUCT_STATIC_BULK_REQUEST';
export const UPDATE_PRODUCT_STATIC_BULK_SUCCESS = 'UPDATE_PRODUCT_STATIC_BULK_SUCCESS';
export const UPDATE_PRODUCT_STATIC_BULK_FAIL = 'UPDATE_PRODUCT_STATIC_BULK_FAIL';

export const UPDATE_LIVE_PRODUCT_ALIAS_REQUEST = 'UPDATE_LIVE_PRODUCT_ALIAS_REQUEST';
export const UPDATE_LIVE_PRODUCT_ALIAS_SUCCESS = 'UPDATE_LIVE_PRODUCT_ALIAS_SUCCESS';
export const UPDATE_LIVE_PRODUCT_ALIAS_FAIL = 'UPDATE_LIVE_PRODUCT_ALIAS_FAIL';

export const DOWNLOAD_INVENTORY_REQUEST = 'DOWNLOAD_INVENTORY_REQUEST';
export const DOWNLOAD_INVENTORY_SUCCESS = 'DOWNLOAD_INVENTORY_SUCCESS';
export const DOWNLOAD_INVENTORY_FAIL = 'DOWNLOAD_INVENTORY_FAIL';
