export const GET_DAILY_PICK_LIST_REQUEST = 'GET_DAILY_PICK_LIST_REQUEST';
export const GET_DAILY_PICK_LIST_SUCCESS = 'GET_DAILY_PICK_LIST_SUCCESS';
export const GET_DAILY_PICK_LIST_FAIL = 'GET_DAILY_PICK_LIST_FAIL';
