export const GET_LIST_ORDER_REQUEST = 'GET_LIST_ORDER_REQUEST';
export const GET_LIST_ORDER_SUCCESS = 'GET_LIST_ORDER_SUCCESS';
export const GET_LIST_ORDER_FAIL = 'GET_LIST_ORDER_FAIL';

export const LOAD_MORE_LIST_ORDER_REQUEST = 'LOAD_MORE_LIST_ORDER_REQUEST';
export const LOAD_MORE_LIST_ORDER_SUCCESS = 'LOAD_MORE_LIST_ORDER_SUCCESS';
export const LOAD_MORE_LIST_ORDER_FAIL = 'LOAD_MORE_LIST_ORDER_FAIL';

export const GET_LIST_ORDER_RETURN_REQUEST = 'GET_LIST_ORDER_RETURN_REQUEST';
export const GET_LIST_ORDER_RETURN_SUCCESS = 'GET_LIST_ORDER_RETURN_SUCCESS';
export const GET_LIST_ORDER_RETURN_FAIL = 'GET_LIST_ORDER_RETURN_FAIL';
