export const CREATE_RETAILER_WAREHOUSE_REQUEST = 'CREATE_RETAILER_WAREHOUSE_REQUEST';
export const CREATE_RETAILER_WAREHOUSE_SUCCESS = 'CREATE_RETAILER_WAREHOUSE_SUCCESS';
export const CREATE_RETAILER_WAREHOUSE_FAIL = 'CREATE_RETAILER_WAREHOUSE_FAIL';

export const GET_RETAILER_WAREHOUSE_REQUEST = 'GET_RETAILER_WAREHOUSE_REQUEST';
export const GET_RETAILER_WAREHOUSE_SUCCESS = 'GET_RETAILER_WAREHOUSE_SUCCESS';
export const GET_RETAILER_WAREHOUSE_FAIL = 'GET_RETAILER_WAREHOUSE_FAIL';

export const GET_RETAILER_WAREHOUSE_DETAIL_REQUEST = 'GET_RETAILER_WAREHOUSE_DETAIL_REQUEST';
export const GET_RETAILER_WAREHOUSE_DETAIL_SUCCESS = 'GET_RETAILER_WAREHOUSE_DETAIL_SUCCESS';
export const GET_RETAILER_WAREHOUSE_DETAIL_FAIL = 'GET_RETAILER_WAREHOUSE_DETAIL_FAIL';

export const UPDATE_RETAILER_WAREHOUSE_REQUEST = 'UPDATE_RETAILER_WAREHOUSE_REQUEST';
export const UPDATE_RETAILER_WAREHOUSE_SUCCESS = 'UPDATE_RETAILER_WAREHOUSE_SUCCESS';
export const UPDATE_RETAILER_WAREHOUSE_FAIL = 'UPDATE_RETAILER_WAREHOUSE_FAIL';

export const DELETE_RETAILER_WAREHOUSE_REQUEST = 'DELETE_RETAILER_WAREHOUSE_REQUEST';
export const DELETE_RETAILER_WAREHOUSE_SUCCESS = 'DELETE_RETAILER_WAREHOUSE_SUCCESS';
export const DELETE_RETAILER_WAREHOUSE_FAIL = ' DELETE_RETAILER_WAREHOUSE_FAIL';
