export const CREATE_RETAILER_REQUEST = 'CREATE_RETAILER_REQUEST';
export const CREATE_RETAILER_SUCCESS = 'CREATE_RETAILER_SUCCESS';
export const CREATE_RETAILER_FAIL = 'CREATE_RETAILER_FAIL';

export const GET_RETAILER_REQUEST = 'GET_RETAILER_REQUEST';
export const GET_RETAILER_SUCCESS = 'GET_RETAILER_SUCCESS';
export const GET_RETAILER_FAIL = 'GET_RETAILER_FAIL';

export const GET_DETAIL_RETAILER_REQUEST = 'GET_DETAIL_RETAILER_REQUEST';
export const GET_DETAIL_RETAILER_SUCCESS = 'GET_DETAIL_RETAILER_SUCCESS';
export const GET_DETAIL_RETAILER_FAIL = 'GET_DETAIL_RETAILER_FAIL';

export const UPDATE_RETAILER_REQUEST = 'UPDATE_RETAILER_REQUEST';
export const UPDATE_RETAILER_SUCCESS = 'UPDATE_RETAILER_SUCCESS';
export const UPDATE_RETAILER_FAIL = 'UPDATE_RETAILER_FAIL';

export const DELETE_RETAILER_REQUEST = 'DELETE_RETAILER_REQUEST';
export const DELETE_RETAILER_SUCCESS = 'DELETE_RETAILER_SUCCESS';
export const DELETE_RETAILER_FAIL = ' DELETE_RETAILER_FAIL';

export const DETAIL_RETAILER_REQUEST = 'DETAIL_RETAILER_REQUEST';
export const DETAIL_RETAILER_SUCCESS = 'DETAIL_RETAILER_SUCCESS';
export const DETAIL_RETAILER_FAIL = 'DETAIL_RETAILER_FAIL';

export const CREATE_SFTP_REQUEST = 'CREATE_SFTP_REQUEST';
export const CREATE_SFTP_SUCCESS = 'CREATE_SFTP_SUCCESS';
export const CREATE_SFTP_FAIL = 'CREATE_SFTP_FAIL';

export const GET_SFTP_REQUEST = 'GET_SFTP_REQUEST';
export const GET_SFTP_SUCCESS = 'GET_SFTP_SUCCESS';
export const GET_SFTP_FAIL = 'GET_SFTP_FAIL';

export const UPDATE_SFTP_REQUEST = 'UPDATE_SFTP_REQUEST';
export const UPDATE_SFTP_SUCCESS = 'UPDATE_SFTP_SUCCESS';
export const UPDATE_SFTP_FAIL = 'UPDATE_SFTP_FAIL';

export const CREATE_SHIP_FROM_REQUEST = 'CREATE_SHIP_FROM_REQUEST';
export const CREATE_SHIP_FROM_SUCCESS = 'CREATE_SHIP_FROM_SUCCESS';
export const CREATE_SHIP_FROM_FAIL = 'CREATE_SHIP_FROM_FAIL';

export const UPDATE_SHIP_FROM_REQUEST = 'UPDATE_SHIP_FROM_REQUEST';
export const UPDATE_SHIP_FROM_SUCCESS = 'UPDATE_SHIP_FROM_SUCCESS';
export const UPDATE_SHIP_FROM_FAIL = 'UPDATE_SHIP_FROM_FAIL';
