export const GET_ORGANIZATION_REQUEST = 'GET_ORGANIZATION_REQUEST';
export const GET_ORGANIZATION_SUCCESS = 'GET_ORGANIZATION_SUCCESS';
export const GET_ORGANIZATION_FAIL = 'GET_ORGANIZATION_FAIL';

export const GET_ORGANIZATION_MEMBER_REQUEST = 'GET_ORGANIZATION_MEMBER_REQUEST';
export const GET_ORGANIZATION_MEMBER_SUCCESS = 'GET_ORGANIZATION_MEMBER_SUCCESS';
export const GET_ORGANIZATION_MEMBER_FAIL = 'GET_ORGANIZATION_MEMBER_FAIL';

export const CREATE_ORGANIZATION_REQUEST = 'CREATE_ORGANIZATION_REQUEST';
export const CREATE_ORGANIZATION_SUCCESS = 'CREATE_ORGANIZATION_SUCCESS';
export const CREATE_ORGANIZATION_FAIL = 'CREATE_ ORGANIZATION_FAIL';

export const DELETE_ORGANIZATION_REQUEST = 'DELETE_ORGANIZATION_REQUEST';
export const DELETE_ORGANIZATION_SUCCESS = 'DELETE_ORGANIZATION_SUCCESS';
export const DELETE_ORGANIZATION_FAIL = 'DELETE_ ORGANIZATION_FAIL';

export const UPDATE_ORGANIZATION_REQUEST = 'UPDATE_ORGANIZATION_REQUEST';
export const UPDATE_ORGANIZATION_SUCCESS = 'UPDATE_ORGANIZATION_SUCCESS';
export const UPDATE_ORGANIZATION_FAIL = 'UPDATE_ ORGANIZATION_FAIL';

export const INVITE_MEMBER_REQUEST = 'INVITE_MEMBER_REQUEST';
export const INVITE_MEMBER_SUCCESS = 'INVITE_MEMBER_SUCCESS';
export const INVITE_MEMBER_FAIL = 'INVITE_MEMBER_FAIL';

export const DELETE_MEMBER_REQUEST = 'DELETE_MEMBER_REQUEST';
export const DELETE_MEMBER_SUCCESS = 'DELETE_MEMBER_SUCCESS';
export const DELETE_MEMBER_FAIL = 'DELETE_MEMBER_FAIL';

export const UPDATE_INVITE_MEMBER_REQUEST = 'UPDATE_INVITE_MEMBER_REQUEST';
export const UPDATE_INVITE_MEMBER_SUCCESS = 'UPDATE_INVITE_MEMBER_SUCCESS';
export const UPDATE_INVITE_MEMBER_FAIL = 'UPDATE_INVITE_MEMBER_FAIL';

export const GET_ORGANIZATION_DETAIL_REQUEST = 'GET_ORGANIZATION_DETAIL_REQUEST';
export const GET_ORGANIZATION_DETAIL_SUCCESS = 'GET_ORGANIZATION_DETAIL_SUCCESS';
export const GET_ORGANIZATION_DETAIL_FAIL = 'GET_ORGANIZATION_DETAIL_FAIL';

export const GET_ROLE_REQUEST = 'GET_ROLE_REQUEST';
export const GET_ROLE_SUCCESS = 'GET_ROLE_SUCCESS';
export const GET_ROLE_FAIL = 'GET_ROLE_FAIL';

export const LOAD_MORE_MEMBER_REQUEST = 'LOAD_MORE_MEMBER_REQUEST';
export const LOAD_MORE_MEMBER_SUCCESS = 'LOAD_MORE_MEMBER_SUCCESS';
export const LOAD_MORE_MEMBER_FAIL = 'LOAD_MORE_MEMBER_FAIL';
