export const CREATE_RETAILER_CARRIER_REQUEST = 'CREATE_RETAILER_CARRIER_REQUEST';
export const CREATE_RETAILER_CARRIER_SUCCESS = 'CREATE_RETAILER_CARRIER_SUCCESS';
export const CREATE_RETAILER_CARRIER_FAIL = 'CREATE_RETAILER_CARRIER_FAIL';

export const GET_RETAILER_CARRIER_REQUEST = 'GET_RETAILER_CARRIER_REQUEST';
export const GET_RETAILER_CARRIER_SUCCESS = 'GET_RETAILER_CARRIER_SUCCESS';
export const GET_RETAILER_CARRIER_FAIL = 'GET_RETAILER_CARRIER_FAIL';

export const GET_RETAILER_CARRIER_DETAIL_REQUEST = 'GET_RETAILER_CARRIER_DETAIL_REQUEST';
export const GET_RETAILER_CARRIER_DETAIL_SUCCESS = 'GET_RETAILER_CARRIER_DETAIL_SUCCESS';
export const GET_RETAILER_CARRIER_DETAIL_FAIL = 'GET_RETAILER_CARRIER_DETAIL_FAIL';

export const UPDATE_RETAILER_CARRIER_REQUEST = 'UPDATE_RETAILER_CARRIER_REQUEST';
export const UPDATE_RETAILER_CARRIER_SUCCESS = 'UPDATE_RETAILER_CARRIER_SUCCESS';
export const UPDATE_RETAILER_CARRIER_FAIL = 'UPDATE_RETAILER_CARRIER_FAIL';

export const DELETE_RETAILER_CARRIER_REQUEST = 'DELETE_RETAILER_CARRIER_REQUEST';
export const DELETE_RETAILER_CARRIER_SUCCESS = 'DELETE_RETAILER_CARRIER_SUCCESS';
export const DELETE_RETAILER_CARRIER_FAIL = ' DELETE_RETAILER_CARRIER_FAIL';

export const GET_SERVICE_REQUEST = 'GET_SERVICE_REQUEST';
export const GET_SERVICE_SUCCESS = 'GET_SERVICE_SUCCESS';
export const GET_SERVICE_FAIL = 'GET_SERVICE_FAIL';
